### ISSUE TITLE
Output must contain `"version": 2`

### ISSUE THREAD

**Issue by verdammelt** [exercism/common-lisp-test-runner#30]
If it does not then the website will only report 'pass/fail' rather than more detailed information.

(ref: https://exercism.lol/docs/building/tooling/test-runners/interface)

**Comment by TheLostLambda** [comment]
Hey @verdammelt ! Sorry I've been away for ages! I took on way too much work recently and things are just starting to wind down, but [I think I've implemented this](https://github.com/exercism/common-lisp-test-runner/blob/ffa8fdb096ad4d34e10d25ab1a37b951286adb31/src/test-runner/test-runner.lisp#L85)! It was in my last commit I think :)

**Comment by verdammelt** [comment]
oh look at that! quite right. Not sure how/why i missed that.

So... nothing to see here... carry on... :)
