### ISSUE TITLE
Test Runner stuck in state "Processing"

### ISSUE THREAD

**Issue by dviererbe** [exercism/common-lisp-test-runner#43]
I submitted a solution to the common lisp track yesterday and it is still stuck in state "_Processing_".

Link to the solution in question: https://exercism.org/tracks/common-lisp/exercises/pizza-pi/solutions/dviererbe

**Comment by verdammelt** [comment]
@iHiD  / @ErikSchierboom Sorry to bother you but what is the way to debug this problem? The test runner has not been updated in a while so I'm guessing it is more of an infrastructrure problem rather than a test-runner problem.

Thanks in advance

**Comment by iHiD** [comment]
I've kicked it. @dviererbe Does it look any better now?

**Comment by dviererbe** [comment]
@iHiD It passed. Thanks :)

@verdammelt Where should I report infrastructrure problems in the future?

**Comment by verdammelt** [comment]
> Where should I report infrastructure problems...

That is a good question!

@iHiD where should a student go to report this sort of thing? Should they create an issue in https://github.com/exercism/exercism/issues?

**Comment by iHiD** [comment]
For now, exercism/exercism is great yes. And then overtime we'll have systems in place that mean these sort of errors sort themselves out over time.
