### ISSUE TITLE
Set executable bit on bin/run.sh

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/common-lisp-test-runner#5]
When trying to run the test runner, the following error occurs:

> \"exec: \\\"bin/run.sh\\\": permission denied\"\n"

This probably means that the file does not have the executable bit set in Git.

**Comment by TheLostLambda** [comment]
Haha, that was the only file in that directory without the executable bit flipped! Should be better now.

**Comment by ErikSchierboom** [comment]
Looks good! Closing this.
